### PR TITLE
Support For Multiple Embeds

### PR DESCRIPTION
**Pull request by chtzvt**
Hello all, 

This PR adds support for multiple embeds as discussed in #25. I've rolled the changes I've made for this into the original shortcode, and added a new partial responsible for loading pdf.js and the shortcode styles. 

Give it a test and let me know what you think.

### CODE REVIEW

**Comment by ctrezevant** [comment]
@anvithks Any thoughts on this?

**Comment by anvithks** [comment]
> @anvithks Any thoughts on this?

I am sorry but I haven't been able to test this yet.
I will try to spend some time over the weekend and merge the PR if all OK.

Thanks @ctrezevant .

**Comment by RoneoOrg** [comment]
Hi @ctrezevant , thanks for sharing this code!

PR #32 is a proposal mixing your code and this little trick: splitting the code into multiple files can be avoided. See [0b75911](https://github.com/RoneoOrg/hugo-embed-pdf-shortcode-roneo/commit/0b759112a024dc79b72a7425bf50688217f5e8b0) and [this discussion on discourse.gohugo.io](https://discourse.gohugo.io/t/how-to-add-css-from-a-theme-component/39390).

I've tested #32 and it works fine. If it's not working for you, please double-check the commits https://github.com/anvithks/hugo-embed-pdf-shortcode/pull/32/commits/f7a8fecb847c1845d35683c7a85eb82f751aabd3 and https://github.com/anvithks/hugo-embed-pdf-shortcode/pull/32/commits/e3642f0d37a806d5735e5f670e3e31e1f4da6841. They are required to make this shortcode work with my theme (Papermod) but your setup may be different

**Comment by ctrezevant** [comment]
Glad to see this moving forward! Everything looks solid after a cursory review.

**Comment by anvithks** [comment]
@chtzvt Closing this as it was added to #32 and merged with your commits.

**Pull request closed without merging**
